name = "StaticModules"
uuid = "0e73dd9d-f2ce-43e7-894a-685dc1ae04f6"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.1.0"

[deps]
JuliaVariables = "b14d175d-62b4-44ba-8fb7-3064adc8c3ec"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]